import Head from "next/head";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import Silder from "@/components/Silder/Silder";
import CardLayout from "@/components/CardLayout/CardLayout";
import { get } from "@/utils/api/apiMethods";

export default function Home() {
  const [bannerData, setBannerData  ] = useState([]);
  const [cardData, setCardData] = useState([])
  
  useEffect(() => {
    callHomePageApi();
  }, [])

  const callHomePageApi = async() => {
    const response = await get({url: "http://localhost:8000/api/v2/pages/7/"});
    console.log("response", response);
    if (response) {
      if (response?.banner_images?.length) {
        setBannerData(response.banner_images)
      }
      if (response?.dataCards?.length) {
        setCardData(response.dataCards)
      }
    }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Silder bannerData={bannerData} />
        <CardLayout data={cardData} />
    </>
  );
}
