import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "src/styles/Home.module.css";
import ContentPage from "@/components/ContentPage";
import axios from "axios";
import { BrPage } from "@bloomreach/react-sdk";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BrPage configuration={{
            endpoint: 'https://developers.bloomreach.io/delivery/site/v1/channels/getting-started/pages',
            httpClient: axios
          }} mapping={{ ContentPage }}>
        </BrPage>
      </main>
    </>
  );
}
