import Head from "next/head";
import { Inter } from "next/font/google";
import type { AppContext, AppProps } from 'next/app';
import styles from "src/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";

export async function getServerSideProps(appContext: any) {
  console.log("data", appContext)
  // const requestHeaders = appContext.ctx?.req;
  const {locale} = appContext;
  console.log("locale", locale)
  let greeting = "";
  if (locale === "en-US") {
    greeting = "Hello I am en";
  } else if (locale === "de") {
    greeting = "Hello I am de";
  } else if (locale === "fr") {
    greeting = "Hello i am fr";
  }

  return {
    props: {
      greeting
    },
  };

}

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{display:"flex", flexDirection: "column"}}>
   
        {props.greeting}
        <br />
        <br />
        <br />
        <Link href="/" locale="fr">
          To FR
        </Link>
        <Link href="/" locale="de">
          To DE
        </Link>
        <Link href="/" locale="en-Us">
          To EN
        </Link>
        </div>
     
      </main>
    </>
  );
}
