import Head from "next/head";
import { Inter } from "next/font/google";
import type { AppContext, AppProps } from "next/app";
import styles from "src/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
import { get, post } from "@/utils/api/apiMethods";

export async function getServerSideProps(appContext: any) {
  const { locale, req } = appContext;
  console.log("locale", req.headers.host);
  let greeting = "";
  if (locale === "en-US") {
    greeting = "Hello I am en";
  } else if (locale === "de") {
    greeting = "Hello I am de";
  } else if (locale === "fr") {
    greeting = "Hello i am fr";
  }

  const response = await post({
    url: "http://www.example.com/api/hello",
    obj: { domain: req.headers.host },
  });

  console.log("response", response);

  return {
    props: {
      greeting,
      domain: response.name,
    },
  };
}

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Home Page Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ display: "flex", flexDirection: "column" }}>
          {props.domain}
        </div>
      </main>
    </>
  );
}
